# Pandas Library

**Key Data Structures in panda**

1.Series
2.Data Frames

In [1]:
import pandas as pd

In [2]:
s=pd.Series([1,2,3,4,5])     #Labeled array               1D

In [3]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])

In [5]:
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [6]:
df=pd.DataFrame({"names" : ['harry','ali','hassan','hanain'] ,"marks":[10,20,30,40]})            #2D

In [7]:
print(df)

    names  marks
0   harry     10
1     ali     20
2  hassan     30
3  hanain     40

In [8]:
df=pd.read_csv("customers-100.csv")

In [9]:
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,KHID4HiDzp,Hector,Huang,Baxter Group,Port Ianshire,Finland,6233837777,(302)564-9011x928,janecooper@chambers-underwood.com,2022-06-12,http://gamble.org/
1,2,W50PcDdk1a,Marcus,Hahn,Rich-Santos,West Erica,New Zealand,250-574-1941x405,+1-810-810-1744x956,mercedes43@hooper-newman.com,2020-12-06,http://key.com/
2,3,acQ3W8B4t8,Cassie,Walsh,Shea-Ewing,New Joanne,Cayman Islands,001-568-835-1828,603-949-6270x4521,eddiedelacruz@malone.com,2022-09-25,https://woods.com/
3,4,4QMeOJZ0vf,Erica,Powers,"Petersen, Sloan and Boyer",Patriciaberg,Svalbard & Jan Mayen Islands,483.525.2396,001-639-783-4487x497,waynepeters@melendez.com,2020-06-05,https://www.carlson-cantrell.com/
4,5,GXdMtnn172,Carl,Kelley,"Hale, Williamson and Bates",New Danberg,Trinidad and Tobago,(313)729-8953,928.736.3321,derek18@douglas-travis.org,2026-04-23,http://tapia.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,SV50Zl6Yrt,Lonnie,Simmons,"Coleman, Shea and Solis",North Kara,Australia,+1-935-980-3224,+1-882-969-1339x9768,sherry26@cross.net,2024-02-16,http://www.brady.com/
96,97,HVSGs43yc1,Raymond,Decker,Yoder Ltd,Tommouth,Saint Martin,(844)596-3986,(269)242-4510,madisonmurillo@leach.com,2025-04-07,http://www.fletcher.com/
97,98,vHpSg22tjc,Rick,Dillon,Mercer-Flowers,West Dale,Paraguay,628-542-9143x3484,285-991-1643x1682,gravesnoah@hampton.com,2024-12-28,http://www.villanueva.com/
98,99,TZOMKyTZgW,Tammy,Padilla,Robbins PLC,Dodsonborough,Maldives,(232)805-1256x78944,(220)979-9910,carlosgreer@orozco-david.org,2021-07-15,https://bailey.com/
99,100,Tlgu4ySmkG,Earl,Guerrero,"Conrad, Hartman and Mann",Hamptonshire,Congo,3417177923,(465)919-5684,alecwells@sampson.net,2021-07-22,https://graham.com/

In [10]:
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,KHID4HiDzp,Hector,Huang,Baxter Group,Port Ianshire,Finland,6233837777,(302)564-9011x928,janecooper@chambers-underwood.com,2022-06-12,http://gamble.org/
1,2,W50PcDdk1a,Marcus,Hahn,Rich-Santos,West Erica,New Zealand,250-574-1941x405,+1-810-810-1744x956,mercedes43@hooper-newman.com,2020-12-06,http://key.com/
2,3,acQ3W8B4t8,Cassie,Walsh,Shea-Ewing,New Joanne,Cayman Islands,001-568-835-1828,603-949-6270x4521,eddiedelacruz@malone.com,2022-09-25,https://woods.com/
3,4,4QMeOJZ0vf,Erica,Powers,"Petersen, Sloan and Boyer",Patriciaberg,Svalbard & Jan Mayen Islands,483.525.2396,001-639-783-4487x497,waynepeters@melendez.com,2020-06-05,https://www.carlson-cantrell.com/
4,5,GXdMtnn172,Carl,Kelley,"Hale, Williamson and Bates",New Danberg,Trinidad and Tobago,(313)729-8953,928.736.3321,derek18@douglas-travis.org,2026-04-23,http://tapia.com/

In [11]:
df.tail()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
95,96,SV50Zl6Yrt,Lonnie,Simmons,"Coleman, Shea and Solis",North Kara,Australia,+1-935-980-3224,+1-882-969-1339x9768,sherry26@cross.net,2024-02-16,http://www.brady.com/
96,97,HVSGs43yc1,Raymond,Decker,Yoder Ltd,Tommouth,Saint Martin,(844)596-3986,(269)242-4510,madisonmurillo@leach.com,2025-04-07,http://www.fletcher.com/
97,98,vHpSg22tjc,Rick,Dillon,Mercer-Flowers,West Dale,Paraguay,628-542-9143x3484,285-991-1643x1682,gravesnoah@hampton.com,2024-12-28,http://www.villanueva.com/
98,99,TZOMKyTZgW,Tammy,Padilla,Robbins PLC,Dodsonborough,Maldives,(232)805-1256x78944,(220)979-9910,carlosgreer@orozco-david.org,2021-07-15,https://bailey.com/
99,100,Tlgu4ySmkG,Earl,Guerrero,"Conrad, Hartman and Mann",Hamptonshire,Congo,3417177923,(465)919-5684,alecwells@sampson.net,2021-07-22,https://graham.com/

In [12]:
df.describe()

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    str
 2   First Name         100 non-null    str
 3   Last Name          100 non-null    str
 4   Company            100 non-null    str
 5   City               100 non-null    str
 6   Country            100 non-null    str
 7   Phone 1            100 non-null    str
 8   Phone 2            100 non-null    str
 9   Email              100 non-null    str
 10  Subscription Date  100 non-null    str
 11  Website            100 non-null    str
dtypes: int64(1), str(11)
memory usage: 9.5 KB

# Data Selection

In [14]:
df["Customer Id"]

0     KHID4HiDzp
1     W50PcDdk1a
2     acQ3W8B4t8
3     4QMeOJZ0vf
4     GXdMtnn172
         ...
95    SV50Zl6Yrt
96    HVSGs43yc1
97    vHpSg22tjc
98    TZOMKyTZgW
99    Tlgu4ySmkG
Name: Customer Id, Length: 100, dtype: str

In [15]:
type(df["Customer Id"])

pandas.Series

In [16]:
df[["Customer Id","First Name"]]

   Customer Id First Name
0   KHID4HiDzp     Hector
1   W50PcDdk1a     Marcus
2   acQ3W8B4t8     Cassie
3   4QMeOJZ0vf      Erica
4   GXdMtnn172       Carl
..         ...        ...
95  SV50Zl6Yrt     Lonnie
96  HVSGs43yc1    Raymond
97  vHpSg22tjc       Rick
98  TZOMKyTZgW      Tammy
99  Tlgu4ySmkG       Earl

[100 rows x 2 columns]

In [17]:
df.iloc[0]       #1st row detail

Index                                                1
Customer Id                                 KHID4HiDzp
First Name                                      Hector
Last Name                                        Huang
Company                                   Baxter Group
City                                     Port Ianshire
Country                                        Finland
Phone 1                                     6233837777
Phone 2                              (302)564-9011x928
Email                janecooper@chambers-underwood.com
Subscription Date                           2022-06-12
Website                             http://gamble.org/
Name: 0, dtype: object

In [18]:
df.dropna()      #it delete rows which have missing data

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,KHID4HiDzp,Hector,Huang,Baxter Group,Port Ianshire,Finland,6233837777,(302)564-9011x928,janecooper@chambers-underwood.com,2022-06-12,http://gamble.org/
1,2,W50PcDdk1a,Marcus,Hahn,Rich-Santos,West Erica,New Zealand,250-574-1941x405,+1-810-810-1744x956,mercedes43@hooper-newman.com,2020-12-06,http://key.com/
2,3,acQ3W8B4t8,Cassie,Walsh,Shea-Ewing,New Joanne,Cayman Islands,001-568-835-1828,603-949-6270x4521,eddiedelacruz@malone.com,2022-09-25,https://woods.com/
3,4,4QMeOJZ0vf,Erica,Powers,"Petersen, Sloan and Boyer",Patriciaberg,Svalbard & Jan Mayen Islands,483.525.2396,001-639-783-4487x497,waynepeters@melendez.com,2020-06-05,https://www.carlson-cantrell.com/
4,5,GXdMtnn172,Carl,Kelley,"Hale, Williamson and Bates",New Danberg,Trinidad and Tobago,(313)729-8953,928.736.3321,derek18@douglas-travis.org,2026-04-23,http://tapia.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,SV50Zl6Yrt,Lonnie,Simmons,"Coleman, Shea and Solis",North Kara,Australia,+1-935-980-3224,+1-882-969-1339x9768,sherry26@cross.net,2024-02-16,http://www.brady.com/
96,97,HVSGs43yc1,Raymond,Decker,Yoder Ltd,Tommouth,Saint Martin,(844)596-3986,(269)242-4510,madisonmurillo@leach.com,2025-04-07,http://www.fletcher.com/
97,98,vHpSg22tjc,Rick,Dillon,Mercer-Flowers,West Dale,Paraguay,628-542-9143x3484,285-991-1643x1682,gravesnoah@hampton.com,2024-12-28,http://www.villanueva.com/
98,99,TZOMKyTZgW,Tammy,Padilla,Robbins PLC,Dodsonborough,Maldives,(232)805-1256x78944,(220)979-9910,carlosgreer@orozco-david.org,2021-07-15,https://bailey.com/
99,100,Tlgu4ySmkG,Earl,Guerrero,"Conrad, Hartman and Mann",Hamptonshire,Congo,3417177923,(465)919-5684,alecwells@sampson.net,2021-07-22,https://graham.com/

In [19]:
df.fillna(0)   #fill null values with o

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,KHID4HiDzp,Hector,Huang,Baxter Group,Port Ianshire,Finland,6233837777,(302)564-9011x928,janecooper@chambers-underwood.com,2022-06-12,http://gamble.org/
1,2,W50PcDdk1a,Marcus,Hahn,Rich-Santos,West Erica,New Zealand,250-574-1941x405,+1-810-810-1744x956,mercedes43@hooper-newman.com,2020-12-06,http://key.com/
2,3,acQ3W8B4t8,Cassie,Walsh,Shea-Ewing,New Joanne,Cayman Islands,001-568-835-1828,603-949-6270x4521,eddiedelacruz@malone.com,2022-09-25,https://woods.com/
3,4,4QMeOJZ0vf,Erica,Powers,"Petersen, Sloan and Boyer",Patriciaberg,Svalbard & Jan Mayen Islands,483.525.2396,001-639-783-4487x497,waynepeters@melendez.com,2020-06-05,https://www.carlson-cantrell.com/
4,5,GXdMtnn172,Carl,Kelley,"Hale, Williamson and Bates",New Danberg,Trinidad and Tobago,(313)729-8953,928.736.3321,derek18@douglas-travis.org,2026-04-23,http://tapia.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,SV50Zl6Yrt,Lonnie,Simmons,"Coleman, Shea and Solis",North Kara,Australia,+1-935-980-3224,+1-882-969-1339x9768,sherry26@cross.net,2024-02-16,http://www.brady.com/
96,97,HVSGs43yc1,Raymond,Decker,Yoder Ltd,Tommouth,Saint Martin,(844)596-3986,(269)242-4510,madisonmurillo@leach.com,2025-04-07,http://www.fletcher.com/
97,98,vHpSg22tjc,Rick,Dillon,Mercer-Flowers,West Dale,Paraguay,628-542-9143x3484,285-991-1643x1682,gravesnoah@hampton.com,2024-12-28,http://www.villanueva.com/
98,99,TZOMKyTZgW,Tammy,Padilla,Robbins PLC,Dodsonborough,Maldives,(232)805-1256x78944,(220)979-9910,carlosgreer@orozco-david.org,2021-07-15,https://bailey.com/
99,100,Tlgu4ySmkG,Earl,Guerrero,"Conrad, Hartman and Mann",Hamptonshire,Congo,3417177923,(465)919-5684,alecwells@sampson.net,2021-07-22,https://graham.com/

In [20]:
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,KHID4HiDzp,Hector,Huang,Baxter Group,Port Ianshire,Finland,6233837777,(302)564-9011x928,janecooper@chambers-underwood.com,2022-06-12,http://gamble.org/
1,2,W50PcDdk1a,Marcus,Hahn,Rich-Santos,West Erica,New Zealand,250-574-1941x405,+1-810-810-1744x956,mercedes43@hooper-newman.com,2020-12-06,http://key.com/
2,3,acQ3W8B4t8,Cassie,Walsh,Shea-Ewing,New Joanne,Cayman Islands,001-568-835-1828,603-949-6270x4521,eddiedelacruz@malone.com,2022-09-25,https://woods.com/
3,4,4QMeOJZ0vf,Erica,Powers,"Petersen, Sloan and Boyer",Patriciaberg,Svalbard & Jan Mayen Islands,483.525.2396,001-639-783-4487x497,waynepeters@melendez.com,2020-06-05,https://www.carlson-cantrell.com/
4,5,GXdMtnn172,Carl,Kelley,"Hale, Williamson and Bates",New Danberg,Trinidad and Tobago,(313)729-8953,928.736.3321,derek18@douglas-travis.org,2026-04-23,http://tapia.com/

In [21]:
df.rename(columns={"Customer Id" : "id" ,"First Name": "F.N" ,"Last Name" : "L.N" ,"Subscription Date" : "S.Date"})

,Index,id,F.N,L.N,Company,City,Country,Phone 1,Phone 2,Email,S.Date,Website
0,1,KHID4HiDzp,Hector,Huang,Baxter Group,Port Ianshire,Finland,6233837777,(302)564-9011x928,janecooper@chambers-underwood.com,2022-06-12,http://gamble.org/
1,2,W50PcDdk1a,Marcus,Hahn,Rich-Santos,West Erica,New Zealand,250-574-1941x405,+1-810-810-1744x956,mercedes43@hooper-newman.com,2020-12-06,http://key.com/
2,3,acQ3W8B4t8,Cassie,Walsh,Shea-Ewing,New Joanne,Cayman Islands,001-568-835-1828,603-949-6270x4521,eddiedelacruz@malone.com,2022-09-25,https://woods.com/
3,4,4QMeOJZ0vf,Erica,Powers,"Petersen, Sloan and Boyer",Patriciaberg,Svalbard & Jan Mayen Islands,483.525.2396,001-639-783-4487x497,waynepeters@melendez.com,2020-06-05,https://www.carlson-cantrell.com/
4,5,GXdMtnn172,Carl,Kelley,"Hale, Williamson and Bates",New Danberg,Trinidad and Tobago,(313)729-8953,928.736.3321,derek18@douglas-travis.org,2026-04-23,http://tapia.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,SV50Zl6Yrt,Lonnie,Simmons,"Coleman, Shea and Solis",North Kara,Australia,+1-935-980-3224,+1-882-969-1339x9768,sherry26@cross.net,2024-02-16,http://www.brady.com/
96,97,HVSGs43yc1,Raymond,Decker,Yoder Ltd,Tommouth,Saint Martin,(844)596-3986,(269)242-4510,madisonmurillo@leach.com,2025-04-07,http://www.fletcher.com/
97,98,vHpSg22tjc,Rick,Dillon,Mercer-Flowers,West Dale,Paraguay,628-542-9143x3484,285-991-1643x1682,gravesnoah@hampton.com,2024-12-28,http://www.villanueva.com/
98,99,TZOMKyTZgW,Tammy,Padilla,Robbins PLC,Dodsonborough,Maldives,(232)805-1256x78944,(220)979-9910,carlosgreer@orozco-david.org,2021-07-15,https://bailey.com/
99,100,Tlgu4ySmkG,Earl,Guerrero,"Conrad, Hartman and Mann",Hamptonshire,Congo,3417177923,(465)919-5684,alecwells@sampson.net,2021-07-22,https://graham.com/

In [22]:
df.rename(columns={"Customer Id" : "id" ,"First Name": "F.N" ,"Last Name" : "L.N" ,"Subscription Date" : "S.Date"})

,Index,id,F.N,L.N,Company,City,Country,Phone 1,Phone 2,Email,S.Date,Website
0,1,KHID4HiDzp,Hector,Huang,Baxter Group,Port Ianshire,Finland,6233837777,(302)564-9011x928,janecooper@chambers-underwood.com,2022-06-12,http://gamble.org/
1,2,W50PcDdk1a,Marcus,Hahn,Rich-Santos,West Erica,New Zealand,250-574-1941x405,+1-810-810-1744x956,mercedes43@hooper-newman.com,2020-12-06,http://key.com/
2,3,acQ3W8B4t8,Cassie,Walsh,Shea-Ewing,New Joanne,Cayman Islands,001-568-835-1828,603-949-6270x4521,eddiedelacruz@malone.com,2022-09-25,https://woods.com/
3,4,4QMeOJZ0vf,Erica,Powers,"Petersen, Sloan and Boyer",Patriciaberg,Svalbard & Jan Mayen Islands,483.525.2396,001-639-783-4487x497,waynepeters@melendez.com,2020-06-05,https://www.carlson-cantrell.com/
4,5,GXdMtnn172,Carl,Kelley,"Hale, Williamson and Bates",New Danberg,Trinidad and Tobago,(313)729-8953,928.736.3321,derek18@douglas-travis.org,2026-04-23,http://tapia.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,SV50Zl6Yrt,Lonnie,Simmons,"Coleman, Shea and Solis",North Kara,Australia,+1-935-980-3224,+1-882-969-1339x9768,sherry26@cross.net,2024-02-16,http://www.brady.com/
96,97,HVSGs43yc1,Raymond,Decker,Yoder Ltd,Tommouth,Saint Martin,(844)596-3986,(269)242-4510,madisonmurillo@leach.com,2025-04-07,http://www.fletcher.com/
97,98,vHpSg22tjc,Rick,Dillon,Mercer-Flowers,West Dale,Paraguay,628-542-9143x3484,285-991-1643x1682,gravesnoah@hampton.com,2024-12-28,http://www.villanueva.com/
98,99,TZOMKyTZgW,Tammy,Padilla,Robbins PLC,Dodsonborough,Maldives,(232)805-1256x78944,(220)979-9910,carlosgreer@orozco-david.org,2021-07-15,https://bailey.com/
99,100,Tlgu4ySmkG,Earl,Guerrero,"Conrad, Hartman and Mann",Hamptonshire,Congo,3417177923,(465)919-5684,alecwells@sampson.net,2021-07-22,https://graham.com/

In [23]:
#df.rename(columns={"Customer Id" : "id" ,"First Name": "F.N" ,"Last Name" : "L.N" ,"Subscription Date" : "S.Date"})

In [24]:
df.tail()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
95,96,SV50Zl6Yrt,Lonnie,Simmons,"Coleman, Shea and Solis",North Kara,Australia,+1-935-980-3224,+1-882-969-1339x9768,sherry26@cross.net,2024-02-16,http://www.brady.com/
96,97,HVSGs43yc1,Raymond,Decker,Yoder Ltd,Tommouth,Saint Martin,(844)596-3986,(269)242-4510,madisonmurillo@leach.com,2025-04-07,http://www.fletcher.com/
97,98,vHpSg22tjc,Rick,Dillon,Mercer-Flowers,West Dale,Paraguay,628-542-9143x3484,285-991-1643x1682,gravesnoah@hampton.com,2024-12-28,http://www.villanueva.com/
98,99,TZOMKyTZgW,Tammy,Padilla,Robbins PLC,Dodsonborough,Maldives,(232)805-1256x78944,(220)979-9910,carlosgreer@orozco-david.org,2021-07-15,https://bailey.com/
99,100,Tlgu4ySmkG,Earl,Guerrero,"Conrad, Hartman and Mann",Hamptonshire,Congo,3417177923,(465)919-5684,alecwells@sampson.net,2021-07-22,https://graham.com/

In [25]:
#df.rename(columns={"Customer Id" : "id" ,"First Name": "F.N" ,"Last Name" : "L.N" ,"Subscription Date" : "S.Date"},inplace=True)

In [26]:
print(df.columns.tolist())

['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City', 'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date', 'Website']

In [29]:
df["Customer Id"]=df["Customer Id"].astype(str)

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    str
 2   First Name         100 non-null    str
 3   Last Name          100 non-null    str
 4   Company            100 non-null    str
 5   City               100 non-null    str
 6   Country            100 non-null    str
 7   Phone 1            100 non-null    str
 8   Phone 2            100 non-null    str
 9   Email              100 non-null    str
 10  Subscription Date  100 non-null    str
 11  Website            100 non-null    str
dtypes: int64(1), str(11)
memory usage: 9.5 KB

In [31]:
len(df)    #Total rows in datframe

100

In [32]:
df["Zeros"]=[0 for i in range(len(df))]    #add new columns

In [33]:
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website,Zeros
0,1,KHID4HiDzp,Hector,Huang,Baxter Group,Port Ianshire,Finland,6233837777,(302)564-9011x928,janecooper@chambers-underwood.com,2022-06-12,http://gamble.org/,0
1,2,W50PcDdk1a,Marcus,Hahn,Rich-Santos,West Erica,New Zealand,250-574-1941x405,+1-810-810-1744x956,mercedes43@hooper-newman.com,2020-12-06,http://key.com/,0
2,3,acQ3W8B4t8,Cassie,Walsh,Shea-Ewing,New Joanne,Cayman Islands,001-568-835-1828,603-949-6270x4521,eddiedelacruz@malone.com,2022-09-25,https://woods.com/,0
3,4,4QMeOJZ0vf,Erica,Powers,"Petersen, Sloan and Boyer",Patriciaberg,Svalbard & Jan Mayen Islands,483.525.2396,001-639-783-4487x497,waynepeters@melendez.com,2020-06-05,https://www.carlson-cantrell.com/,0
4,5,GXdMtnn172,Carl,Kelley,"Hale, Williamson and Bates",New Danberg,Trinidad and Tobago,(313)729-8953,928.736.3321,derek18@douglas-travis.org,2026-04-23,http://tapia.com/,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,SV50Zl6Yrt,Lonnie,Simmons,"Coleman, Shea and Solis",North Kara,Australia,+1-935-980-3224,+1-882-969-1339x9768,sherry26@cross.net,2024-02-16,http://www.brady.com/,0
96,97,HVSGs43yc1,Raymond,Decker,Yoder Ltd,Tommouth,Saint Martin,(844)596-3986,(269)242-4510,madisonmurillo@leach.com,2025-04-07,http://www.fletcher.com/,0
97,98,vHpSg22tjc,Rick,Dillon,Mercer-Flowers,West Dale,Paraguay,628-542-9143x3484,285-991-1643x1682,gravesnoah@hampton.com,2024-12-28,http://www.villanueva.com/,0
98,99,TZOMKyTZgW,Tammy,Padilla,Robbins PLC,Dodsonborough,Maldives,(232)805-1256x78944,(220)979-9910,carlosgreer@orozco-david.org,2021-07-15,https://bailey.com/,0
99,100,Tlgu4ySmkG,Earl,Guerrero,"Conrad, Hartman and Mann",Hamptonshire,Congo,3417177923,(465)919-5684,alecwells@sampson.net,2021-07-22,https://graham.com/,0

In [34]:
def fx(a):
    return a+1
df["Zeros1"]=df["Zeros"].apply(fx)

In [35]:
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website,Zeros,Zeros1
0,1,KHID4HiDzp,Hector,Huang,Baxter Group,Port Ianshire,Finland,6233837777,(302)564-9011x928,janecooper@chambers-underwood.com,2022-06-12,http://gamble.org/,0,1
1,2,W50PcDdk1a,Marcus,Hahn,Rich-Santos,West Erica,New Zealand,250-574-1941x405,+1-810-810-1744x956,mercedes43@hooper-newman.com,2020-12-06,http://key.com/,0,1
2,3,acQ3W8B4t8,Cassie,Walsh,Shea-Ewing,New Joanne,Cayman Islands,001-568-835-1828,603-949-6270x4521,eddiedelacruz@malone.com,2022-09-25,https://woods.com/,0,1
3,4,4QMeOJZ0vf,Erica,Powers,"Petersen, Sloan and Boyer",Patriciaberg,Svalbard & Jan Mayen Islands,483.525.2396,001-639-783-4487x497,waynepeters@melendez.com,2020-06-05,https://www.carlson-cantrell.com/,0,1
4,5,GXdMtnn172,Carl,Kelley,"Hale, Williamson and Bates",New Danberg,Trinidad and Tobago,(313)729-8953,928.736.3321,derek18@douglas-travis.org,2026-04-23,http://tapia.com/,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,SV50Zl6Yrt,Lonnie,Simmons,"Coleman, Shea and Solis",North Kara,Australia,+1-935-980-3224,+1-882-969-1339x9768,sherry26@cross.net,2024-02-16,http://www.brady.com/,0,1
96,97,HVSGs43yc1,Raymond,Decker,Yoder Ltd,Tommouth,Saint Martin,(844)596-3986,(269)242-4510,madisonmurillo@leach.com,2025-04-07,http://www.fletcher.com/,0,1
97,98,vHpSg22tjc,Rick,Dillon,Mercer-Flowers,West Dale,Paraguay,628-542-9143x3484,285-991-1643x1682,gravesnoah@hampton.com,2024-12-28,http://www.villanueva.com/,0,1
98,99,TZOMKyTZgW,Tammy,Padilla,Robbins PLC,Dodsonborough,Maldives,(232)805-1256x78944,(220)979-9910,carlosgreer@orozco-david.org,2021-07-15,https://bailey.com/,0,1
99,100,Tlgu4ySmkG,Earl,Guerrero,"Conrad, Hartman and Mann",Hamptonshire,Congo,3417177923,(465)919-5684,alecwells@sampson.net,2021-07-22,https://graham.com/,0,1

In [36]:
#df.to_csv("customers/export.csv")     from this index column also add in data which is not necessary

In [45]:
import os

print(os.getcwd())

C:\Users\Admin\Taqdees Work

In [46]:
df.to_csv("export.csv", index=False)